// The NSRT note grammar, transcribed from a real note and verified against the
// log it was generated from.
//
// ACCEPTED IN GAME: a note generated by this module was imported into NSRT and
// worked. That is the only test that can prove a format, and it covers the whole
// emit path — the header, `text` lines, `tag:everyone`, and `time` in seconds.
// The two caveats at the bottom survive it, because a note that imports cleanly
// says nothing about either.
//
// VERIFIED against report D4K7nTaXtvr9L2Zk fight 9 (Sszorak, Heroic):
//   - Header:  `EncounterID:3420;Difficulty:Heroic;Name:Sszorak` — no trailing `;`.
//     Matched the fight's encounterID, difficulty 4 = Heroic, and boss name exactly.
//   - Line:    `time:0;ph:1;tag:Niome;spellid:1276452;` — trailing `;` present.
//   - `time` is WHOLE SECONDS FROM PULL START, truncated: of 357 lines whose
//     (player, spell) pair existed in the log, 352 landed within 2s of the claimed
//     time and every offset was positive, between +0.1s and +0.9s. So the writer
//     floors; `Math.floor(ms / 1000)` reproduces it and `Math.round` would not.
//   - `ph` is the phase, 1 throughout a single-phase fight. Times are absolute,
//     NOT relative to the phase — the note ran 0..386s on a 387s pull.
//   - `tag` is a plain character name, unescaped, and non-ASCII names appear
//     verbatim (`Âmâterasu`, `Киалра`, `Tinalthéa`). All 20 resolved to players.
//   - Reminder: `time:133;ph:1;tag:everyone;text:Test Reminder Everyone;` — the
//     same line shape with `text` in place of `spellid`. `tag:everyone` (literal,
//     lowercase) addresses the raid; a character name addresses one player, e.g.
//     `time:228;ph:1;tag:Ennuvathar;text:Text Reminder Person;`. This is the line
//     the generated mechanic warnings use.
//
// STILL NOT VERIFIED, and not settled by the import working:
//   - Whether `text` has any escape for a literal `;`. It is the field
//     separator, so emitting one unescaped would corrupt the line; `sanitizeText`
//     strips them rather than gamble. Nothing we emit contains one, which is
//     exactly why a successful import proves nothing here.
//   - Whether `text` renders markup such as `|cffRRGGBB|r` or `{spell:123}`.
//     Nothing here emits markup, so again the import says nothing about it.
//   - Whether the timers fire *early enough* on a live pull. That is a claim
//     about TIMER_QUANTILE, not about the format, and only a pull can test it.

/** A cooldown assignment: press this spell, at this time, on this character. */
export interface CooldownLine {
  kind: "cooldown";
  /** Whole seconds from pull start, as the format stores it. */
  timeSec: number;
  phase: number | null;
  tag: string;
  spellId: number;
  /**
   * Keys seen on the line beyond the four above, in order. Kept so a note
   * written by a newer NSRT survives a parse/emit round trip unchanged.
   */
  extra: Array<[string, string]>;
}

/**
 * Any line this module does not understand, preserved byte for byte.
 *
 * The point of the whole parser is to let us splice lines into a note the user
 * already has, so anything unrecognised must come back out exactly as it went
 * in. Dropping it would silently destroy someone's raid assignments.
 */
export interface OpaqueLine {
  kind: "opaque";
  raw: string;
}

/** A reminder shown at a time, either to the whole raid or to one player. */
export interface TextLine {
  kind: "text";
  timeSec: number;
  phase: number | null;
  /** `everyone`, or a character name. */
  tag: string;
  text: string;
  extra: Array<[string, string]>;
}

export type NoteLine = CooldownLine | TextLine | OpaqueLine;

/** The literal audience NSRT uses for a raid-wide reminder. */
export const EVERYONE = "everyone";

/**
 * Make a string safe to put in a `text` field.
 *
 * `;` separates fields, so an unescaped one would split the line into nonsense.
 * No escape mechanism was visible in the sample, so the only safe move is to
 * remove them; newlines go for the same reason, since lines are newline-delimited.
 */
export function sanitizeText(text: string): string {
  return text.replace(/[;\r\n]+/g, " ").replace(/\s+/g, " ").trim();
}

export interface NoteHeader {
  encounterId: number | null;
  difficulty: string | null;
  name: string | null;
  /** Every header field in source order, so emitting is lossless. */
  fields: Array<[string, string]>;
}

export interface ParsedNote {
  /** Null when the note does not open with an `EncounterID:` line. */
  header: NoteHeader | null;
  lines: NoteLine[];
  /** True when the source ended with a newline, so emit can restore it. */
  trailingNewline: boolean;
}

/** Semicolon-separated `key:value` pairs. Values may contain `:`, keys may not. */
function splitFields(text: string): Array<[string, string]> {
  const out: Array<[string, string]> = [];
  for (const part of text.split(";")) {
    if (part === "") continue;
    const at = part.indexOf(":");
    if (at < 0) return [];
    out.push([part.slice(0, at), part.slice(at + 1)]);
  }
  return out;
}

function parseHeader(line: string): NoteHeader | null {
  const fields = splitFields(line);
  const get = (key: string) => fields.find(([k]) => k === key)?.[1];
  if (get("EncounterID") == null) return null;
  const id = Number(get("EncounterID"));
  return {
    encounterId: Number.isFinite(id) ? id : null,
    difficulty: get("Difficulty") ?? null,
    name: get("Name") ?? null,
    fields,
  };
}

function parseLine(raw: string): NoteLine {
  const fields = splitFields(raw);
  if (fields.length === 0) return { kind: "opaque", raw };

  const get = (key: string) => fields.find(([k]) => k === key)?.[1];
  const time = get("time");
  const tag = get("tag");
  const spellId = get("spellid");
  const text = get("text");

  // `time` and `tag` are common to both line kinds; the payload decides which.
  // A line missing any of that is something else, and something else is exactly
  // what has to survive untouched.
  if (time == null || tag == null || !/^\d+$/.test(time)) return { kind: "opaque", raw };
  const phaseRaw = get("ph");
  const phase = phaseRaw != null && /^\d+$/.test(phaseRaw) ? Number(phaseRaw) : null;

  if (spellId != null && /^\d+$/.test(spellId)) {
    const known = new Set(["time", "ph", "tag", "spellid"]);
    return {
      kind: "cooldown",
      timeSec: Number(time),
      phase,
      tag,
      spellId: Number(spellId),
      extra: fields.filter(([k]) => !known.has(k)),
    };
  }

  if (text != null) {
    const known = new Set(["time", "ph", "tag", "text"]);
    return {
      kind: "text",
      timeSec: Number(time),
      phase,
      tag,
      text,
      extra: fields.filter(([k]) => !known.has(k)),
    };
  }

  return { kind: "opaque", raw };
}

export function parseNote(text: string): ParsedNote {
  const trailingNewline = /\r?\n$/.test(text);
  const raw = text.split(/\r?\n/);
  if (trailingNewline) raw.pop();

  const header = raw.length > 0 ? parseHeader(raw[0]) : null;
  const body = header ? raw.slice(1) : raw;

  return { header, lines: body.map(parseLine), trailingNewline };
}

export function emitHeader(header: NoteHeader): string {
  return header.fields.map(([k, v]) => `${k}:${v}`).join(";");
}

export function emitLine(line: NoteLine): string {
  if (line.kind === "opaque") return line.raw;
  const fields: Array<[string, string]> = [["time", String(line.timeSec)]];
  if (line.phase != null) fields.push(["ph", String(line.phase)]);
  // Tags are sanitized too: a parsed tag can never contain a `;` (it is the field
  // separator, so the parser would have split there), but a hand-entered name can,
  // and one `;` in a name would corrupt every field after it.
  fields.push(["tag", sanitizeText(line.tag)]);
  if (line.kind === "cooldown") fields.push(["spellid", String(line.spellId)]);
  else fields.push(["text", sanitizeText(line.text)]);
  fields.push(...line.extra);
  // The trailing semicolon is part of the format, unlike on the header.
  return fields.map(([k, v]) => `${k}:${v}`).join(";") + ";";
}

export function emitNote(note: ParsedNote): string {
  const out: string[] = [];
  if (note.header) out.push(emitHeader(note.header));
  for (const line of note.lines) out.push(emitLine(line));
  return out.join("\n") + (note.trailingNewline ? "\n" : "");
}

/**
 * Fight-relative milliseconds to the note's `time` field.
 *
 * Truncating rather than rounding is the measured behaviour, and it is also the
 * safe direction: a timer that fires a fraction early is useful, one that fires
 * late is not.
 */
export function toNoteTime(atMs: number): number {
  return Math.max(0, Math.floor(atMs / 1000));
}
